# Model
model_name_or_path: openai/gpt-oss-20b
attn_implementation: kernels-community/vllm-flash-attn3
torch_dtype: bfloat16

# Dataset
dataset_name: HuggingFaceH4/Multilingual-Thinking
dataset_num_proc: 12

# Hyperparameters
learning_rate: 2.0e-5
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
# Output directory - can be overridden via command line with --output_dir
output_dir: ./models/openai/gpt-oss-20b-multilingual-reasoner-081003
report_to:
- none
push_to_hub: false
seed: 42